### ISSUE TITLE
Segmentation Descriptors missing

### ISSUE THREAD

**Issue by enricovittorini** [futzu/cuei#2]
When parsing the following B64:

/DByAAAAAAAAAv/wBQb+AAAAAABcAhRDVUVJUwIu0X/fAAApTwAAACIAAAIWQ1VFSSxMdth/3wAAKU8AAAA0AAAAAAIWQ1VFSRH5kzZ/3wAAKU8AAAA2AAAAAAIUQ1VFSUWu4aR/3wAAKU8AAAAwAADzsyAa

I only see segmentation_type_id 34 and 52. 54 and 48 are missing.

`{
    "InfoSection": {
        "Name": "Splice Info Section",
        "TableID": "0xfc",
        "SectionSyntaxIndicator": false,
        "Private": false,
        "Reserved": "0x3",
        "SectionLength": 114,
        "ProtocolVersion": 0,
        "EncryptedPacket": false,
        "EncryptionAlgorithm": 0,
        "PtsAdjustment": 0,
        "CwIndex": "0x2",
        "Tier": "0xfff",
        "CommandLength": 5,
        "CommandType": 6
    },
    "Command": {
        "Name": "Time Signal",
        "CommandType": 6,
        "TimeSpecifiedFlag": true
    },
    "DescriptorLoopLength": 92,
    "Descriptors": [
        {
            "Tag": 2,
            "Length": 20,
            "Identifier": "CUEI",
            "Name": "Segmentation Descriptor",
            "SegmentationEventID": "0x53022ed1",
            "ProgramSegmentationFlag": true,
            "SegmentationDurationFlag": true,
            "WebDeliveryAllowedFlag": true,
            "NoRegionalBlackoutFlag": true,
            "ArchiveAllowedFlag": true,
            "DeviceRestrictions": "No Restrictions",
            "SegmentationDuration": 30.08,
            "SegmentationMessage": "Break Start",
            "SegmentationTypeID": 34
        },
        {
            "Tag": 2,
            "Length": 22,
            "Identifier": "CUEI",
            "Name": "Segmentation Descriptor",
            "SegmentationEventID": "0x2c4c76d8",
            "ProgramSegmentationFlag": true,
            "SegmentationDurationFlag": true,
            "WebDeliveryAllowedFlag": true,
            "NoRegionalBlackoutFlag": true,
            "ArchiveAllowedFlag": true,
            "DeviceRestrictions": "No Restrictions",
            "SegmentationDuration": 30.08,
            "SegmentationMessage": "Provider Placement Opportunity Start",
            "SegmentationTypeID": 52
        },
        {
            "Identifier": "\u0002\u0016CU",
            "Name": "Avail Descriptor",
            "ProviderAvailID": 1162416633
        },
        {}
    ],
    "Crc32": 2145320960
}`

**Comment by enricovittorini** [comment]
I think i found the issue: in Descriptors.go


```
		//dscptr.SubSegmentNum = bd.uInt8(8)
		//dscptr.SubSegmentsExpected = bd.uInt8(8)
		dscptr.SubSegmentNum = 0
		dscptr.SubSegmentsExpected = 0
```

tried to comment the lined with value 0 and left uncommented the other and it seems ok.
Any reasons why the were commented? still in dev?

**Comment by futzu** [comment]
The code is still a little in flux, especially the encoding, but not too badly, 
This was probably due to Amazon.
Amazon has been doing some weird stuff lately , like not padding  base64 properly, and in this situation , not including  SubSegmentNum and SubSegmentExpected when they should be included. 


Really , what I should do there is is check the segmentation type id  and if it is one of the four, then check  the descriptor length and see if I have the bits available to read.  Which, I just learned, is what they suggest.
![image](https://github.com/futzu/cuei/assets/52701496/fd4a99fe-94d3-4b5c-b0bb-aa9119791bfd)


I saw you submitted a pull request, I haven't had a chance to look at it yet, but I definitely appreciate it. You seem to be able to follow my code fairly easily  and **I really would like another set eyes on this besides my own.** 

I'll apply your pull and then add a check with descriptor length to make sure the bits are available. 

Adrian

**Comment by futzu** [comment]
Your diagnosis is correct.
```json
a@debian:~/clean/cuei$ ./cuei-cue  '/DByAAAAAAAAAv/wBQb+AAAAAABcAhRDVUVJUwIu0X/fAAApTwAAACIAAAIWQ1VFSSxMdth/3wAAKU8AAAA0AAAAAAIWQ1VFSRH5kzZ/3wAAKU8AAAA2AAAAAAIUQ1VFSUWu4aR/3wAAKU8AAAAwAADzsyAa'
{
    "InfoSection": {
        "Name": "Splice Info Section",
        "TableID": "0xfc",
        "SectionSyntaxIndicator": false,
        "Private": false,
        "Reserved": "0x3",
        "SectionLength": 114,
        "ProtocolVersion": 0,
        "EncryptedPacket": false,
        "EncryptionAlgorithm": 0,
        "PtsAdjustment": 0,
        "CwIndex": "0x2",
        "Tier": "0xfff",
        "CommandLength": 5,
        "CommandType": 6
    },
    "Command": {
        "Name": "Time Signal",
        "CommandType": 6,
        "TimeSpecifiedFlag": true
    },
    "DescriptorLoopLength": 92,
    "Descriptors": [
        {
            "Tag": 2,
            "Length": 20,
            "Identifier": "CUEI",
            "Name": "Segmentation Descriptor",
            "SegmentationEventID": "0x53022ed1",
            "ProgramSegmentationFlag": true,
            "SegmentationDurationFlag": true,
            "WebDeliveryAllowedFlag": true,
            "NoRegionalBlackoutFlag": true,
            "ArchiveAllowedFlag": true,
            "DeviceRestrictions": "No Restrictions",
            "SegmentationDuration": 30.08,
            "SegmentationMessage": "Break Start",
            "SegmentationTypeID": 34
        },
        {
            "Tag": 2,
            "Length": 22,
            "Identifier": "CUEI",
            "Name": "Segmentation Descriptor",
            "SegmentationEventID": "0x2c4c76d8",
            "ProgramSegmentationFlag": true,
            "SegmentationDurationFlag": true,
            "WebDeliveryAllowedFlag": true,
            "NoRegionalBlackoutFlag": true,
            "ArchiveAllowedFlag": true,
            "DeviceRestrictions": "No Restrictions",
            "SegmentationDuration": 30.08,
            "SegmentationMessage": "Provider Placement Opportunity Start",
            "SegmentationTypeID": 52
        },
        {
            "Tag": 2,
            "Length": 22,
            "Identifier": "CUEI",
            "Name": "Segmentation Descriptor",
            "SegmentationEventID": "0x11f99336",
            "ProgramSegmentationFlag": true,
            "SegmentationDurationFlag": true,
            "WebDeliveryAllowedFlag": true,
            "NoRegionalBlackoutFlag": true,
            "ArchiveAllowedFlag": true,
            "DeviceRestrictions": "No Restrictions",
            "SegmentationDuration": 30.08,
            "SegmentationMessage": "Distributor Placement Opportunity Start",
            "SegmentationTypeID": 54
        },
        {
            "Tag": 2,
            "Length": 20,
            "Identifier": "CUEI",
            "Name": "Segmentation Descriptor",
            "SegmentationEventID": "0x45aee1a4",
            "ProgramSegmentationFlag": true,
            "SegmentationDurationFlag": true,
            "WebDeliveryAllowedFlag": true,
            "NoRegionalBlackoutFlag": true,
            "ArchiveAllowedFlag": true,
            "DeviceRestrictions": "No Restrictions",
            "SegmentationDuration": 30.08,
            "SegmentationMessage": "Provider Advertisement Start",
            "SegmentationTypeID": 48
        }
    ],
    "Crc32": 4088602650
}
```

I'll try to get a new  release tonight.

Nice Job.

**Comment by futzu** [comment]
```go
a@debian:~$ go get github.com/futzu/cuei@v1.1.81
go: downloading github.com/futzu/cuei v1.1.81
go: upgraded github.com/futzu/cuei v1.1.79 => v1.1.81


```

**Comment by futzu** [comment]
I'm guessing you're good?
