### ISSUE TITLE
JSON-and-Encode always use "AvailDescriptor.Identifier=CUEI" value even if setter or json static string is modified.

### ISSUE THREAD

**Issue by Murmur** [futzu/cuei#4]
Example app `JSON-and-Encode` does not use `.Identifier="TEST"` or `.Identifier=""` setter? Value is always `CUEI` string, if providing an empty string my thinking was field could also be skipped in a binary output?
https://github.com/futzu/cuei#load-json-and-encode

Online scte parser for debug use: https://www.middleman.tv/scte35-parser

disclaimer: I don't have a deep knowledge of `.Identifer` field, I have not seen it other scte35 examples.

Example output:
`/DAvAAAAAAAAAAFgFAUAAABvf+/+AAHd5v4AUmXA//8BAgAKAAhDVUVJAAABTDVM1CE=`

Example app:
```
package main

import (
	"fmt"
	"github.com/futzu/cuei"
)

func main() {

	js := `{
    "InfoSection": {
        "Name": "Splice Info Section",
        "TableID": "0xfc",
        "SectionSyntaxIndicator": false,
        "Private": false,
        "ProtocolVersion": 0,
        "EncryptedPacket": false,
        "EncryptionAlgorithm": 0,
        "PtsAdjustment": 0,
        "CwIndex": "0x00",
        "Tier": "0x16",
        "CommandType": 5
    },
    "Command": {
        "Name": "Splice Insert",
        "CommandType": 5,
        "SpliceEventID": 1,
        "OutOfNetworkIndicator": true,
        "ProgramSpliceFlag": true,
        "TimeSpecifiedFlag": true,
        "PTS": 0.0
    },
    "Descriptors": [
        {
            "Name": "Avail Descriptor"
        }
    ]
}
`
	cue :=  cuei.Json2Cue(js)	
	cue.AdjustPts(0.0)                      // 0..N seconds(float) pts adjustment
	cue.Command.PTS            = 1.359355   // 0..N seconds(float)
	cue.Command.AvailNum       = 1
	cue.Command.AvailExpected  = 2
	cue.Command.DurationFlag   = true       // write BreakDuration+AutoReturn fields
	cue.Command.BreakAutoReturn= true
	cue.Command.BreakDuration  = 60   // 0..N seconds
	cue.Command.UniqueProgramID= 65535
	cue.Command.SpliceEventID  = 111   // 111 or 222 or any 0..N value
	cue.Descriptors[0].ProviderAvailID=332
	
	fmt.Println("\nBytes:\n\t", cue.Encode())	// Bytes	
	fmt.Println("\nBase64:\n\t",cue.Encode2B64())  	// Base64	
	fmt.Println("\nHex:\n\t",cue.Encode2Hex()) 	// Hex
}
```

edit: edited example for more common default values for clarity.

**Comment by futzu** [comment]
Let me ask you this, why would give me a link to a SCTE-35 parser?  I have written several that are much better. 

The reason it is always set to CUEI is because that is what the specification says it should be, 

![image](https://github.com/futzu/cuei/assets/52701496/348d8bd4-beed-4941-993c-763a044766cb)

**Comment by futzu** [comment]
You need to read the spec man.

  *   `cue.Command.PTS            = 1.359355   // 0..N seconds(float) 1sec=0x015F90/90000`   __wtf?__
       *  __No__. 1 second = 90,000 ticks 
       * cuei shows PTS in seconds,
      *  if you want ticks, __ticks =  seconds *90000__ 
    
 *	cue.Command.BreakAutoReturn= true
       *  __This is correct, however a lot of parsers won't auto-return.__
       *  Don't be lazy, add a cue to return from the break.
        
* `cue.Command.BreakDuration  = 60*90000 // sec*90000`
    *  __No.__  Break Duration is always in seconds.	

*	`//cue.Descriptors[0].Identifier=""`   
       *  __No__,  the identifier shall have the value __ 0x43554549__ or __CUEI__
       
*  `//cue.Descriptors[0].Identifier="TEST"` 
       
      *  __No__,  the identifier shall have the value __ 0x43554549__ or __CUEI__

**Comment by Murmur** [comment]
`>> give me a link to a SCTE-35 parser?` 
No specific reason, just anyone reading this issue may quickly use an online parser for debugging. 

Thanks for the explanation so `CUEI` it is and removing the identifier field from the json template indeed still produced the same value.

My comments were more or less leftovers with random 90KHz bits.

`cue.Command.PTS ` I give value as a second, comment `0x015F90=90000 ticks -> /90000 = 1 sec`

`>>This is correct, however a lot of parsers won't auto-return.`  True, my scte payload is following the data expected by one specific testing app so autoreturn=true flag is given.

`>>cue.Command.BreakDuration  = 60*90000` I give value as a second but that one specific testing app sometimes use magic numbers for testing purpose some may be sane and some very alien numbers.

`cue.Command.DurationFlag   = true    // write BreakDuration+AutoReturn fields`
I missed this field earlier some test data need breakDuration+breakAutoReturn fields in an output binary.
